### PR TITLE
Feature/proguard config

### PR DESCRIPTION
**Pull request by mrsasha**
@skraynick should be tested, everything looks ok but proguard is tricky.

### CODE REVIEW

**Comment by skraynick** [comment]
@mrsasha CR fine, but tests are failing locally failing for me. Are they running ok for you?

**Comment by mrsasha** [comment]
@skraynick I just checked and there's the duplicate exception, the same that you get probably. The funny thing is that I get the same one trying to run tests or build debug on the squashed branch or even regular release 1.2.0 branch. Can you check? How did falco manage to build this at all? :)

In any case, the tests don't depend on proguard and we have rewritten everything anyway on develop so it doesn't matter that much, but... why does this happen now?

**Comment by skraynick** [comment]
@mrsasha I will spend some looking into it today.

**Comment by skraynick** [comment]
@mrsasha so weird. Ok. So I hunted down the problem with sugar. For some super strange reason the 2.1.0 build:gradle:2.1.0 didn't work. Strangely it worked before as you can see from my commit on the android 6 branch. From what I can tell from the git history. We merged in the qube stuff into develop, not sure why that would conflict. I got my android 6 branch working and when I lower the gradle to build:gradle:1.5.0' this branch gives me no issues and all 212 tests pass. I am also going to try the same thing in develop to confirm my findings.

**Comment by mrsasha** [comment]
@skraynick I didn't actually change gradle build plugin in this PR. I have no idea why it wouldn't execute the tests. I just tried it again on both of my PCs and everything works.I have rebased from develop, maybe you could try again, with first running `clean assembleDebug` and then `connectedCheck createDebugCoverageReport`? thx.

**Comment by skraynick** [comment]
log output:
`
07-06 02:00:42.733 17358 17358 D DemoApplication: onCreate application
07-06 02:00:42.785   789   809 D BluetoothManagerService: Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@5f799f:true
07-06 02:00:42.796 17358 17358 V Sensorberg: Can't read macs from BluetoothCrashResolverState.txt
07-06 02:00:42.954 17358 17358 D Sugar   : Fetching properties
07-06 02:00:42.958 17358 17358 E SQLiteLog: (1) no such table: SUGAR_SCAN
07-06 02:00:42.958 17358 17358 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-06 02:00:42.959 17358 17358 E AndroidRuntime: FATAL EXCEPTION: main
07-06 02:00:42.959 17358 17358 E AndroidRuntime: Process: com.sensorberg.sdk.testApp.debug, PID: 17358
07-06 02:00:42.959 17358 17358 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sensorberg.sdk.testApp.debug/com.sensorberg.sdk.demo.DemoActivity}: android.database.sqlite.SQLiteException: no such table: SUGAR_SCAN (code 1): , while compiling: INSERT OR REPLACE  INTO SUGAR_SCAN(PROXIMITY_UUID,SENT_TO_SERVER_TIMESTAMP,IS_ENTRY,ID,PROXIMITY_MAJOR,SENT_TO_SERVER_TIMESTAMP2,PROXIMITY_MINOR,CREATED_AT,EVENT_TIME) VALUES (?,?,?,?,?,?,?,?,?)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: no such table: SUGAR_SCAN (code 1): , while compiling: INSERT OR REPLACE  INTO SUGAR_SCAN(PROXIMITY_UUID,SENT_TO_SERVER_TIMESTAMP,IS_ENTRY,ID,PROXIMITY_MAJOR,SENT_TO_SERVER_TIMESTAMP2,PROXIMITY_MINOR,CREATED_AT,EVENT_TIME) VALUES (?,?,?,?,?,?,?,?,?)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at com.sensorbergorm.SugarRecord.save(SugarRecord.java:280)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at com.sensorbergorm.SugarRecord.save(SugarRecord.java:416)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at com.sensorberg.sdk.demo.DemoActivity.onCreate(DemoActivity.java:80)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
07-06 02:00:42.959 17358 17358 E AndroidRuntime: 	... 9 more
07-06 02:00:42.961   789   800 W ActivityManager:   Force finishing activity com.sensorberg.sdk.testApp.debug/com.sensorberg.sdk.demo.DemoActivity
07-06 02:00:43.265   789   800 I WindowManager: Screenshot max retries 4 of Token{415b853 ActivityRecord{7389042 u0 com.sensorberg.sdk.testApp.debug/com.sensorberg.sdk.demo.DemoActivity t979 f}} appWin=Window{80be59a u0 Starting com.sensorberg.sdk.testApp.debug} drawState=4
07-06 02:00:43.268   789   800 W ActivityManager:   Force finishing activity com.android.settings/.SubSettings
07-06 02:00:43.348   789   889 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
07-06 02:00:43.349   789   889 I OpenGLRenderer: Initialized EGL, version 1.4
07-06 02:00:43.380  1668 17775 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
07-06 02:00:43.768   789   802 W ActivityManager: Activity pause timeout for ActivityRecord{7389042 u0 com.sensorberg.sdk.testApp.debug/com.sensorberg.sdk.demo.DemoActivity t979 f}
07-06 02:00:43.951  3074  3074 D DashboardSummary: rebuildUI took: 89 ms
07-06 02:00:49.374  3232  3309 D BluetoothAdapter: stopLeScan()
07-06 02:00:49.388  3232  3309 D BluetoothAdapter: scan not started yet
07-06 02:00:49.397  3172  3231 D BluetoothAdapter: stopLeScan()
07-06 02:00:49.398  3172  3231 D BluetoothAdapter: scan not started yet
07-06 02:00:49.402  3123  3193 D BluetoothAdapter: stopLeScan()
07-06 02:00:49.402  3123  3193 D BluetoothAdapter: scan not started yet
`

**Comment by mrsasha** [comment]
ok, I rebased and removed the gradle tools update, it's now the same as in develop except for proguard config.

**Pull request merged**
