### PR TITLE
Bugfix/setlogging always displays a toast

### PR DESCRIPTION
**Pull request by skraynick**

### CODE REVIEW

**Comment by falkorichter** [comment]
@skraynick it doesn´t compile. see travis build.

**Comment by skraynick** [comment]
@falkorichter caught the error.  Pushing now.  Also, it appears the toasts are failing tests anyways. Apparently, they should be on the main thread... I like the idea you had, and just leave the logging and not display anything.

**Comment by skraynick** [comment]
@falkorichter I took out the toasts as they were messing with the tests anyways. Apparently, it is not a good idea to use toasts off the UI thread. Also FYI, travis is having issues finding libs Could not GET 'https://plugins.gradle.org/m2/org/sonarsource/scanner/gradle/sonarqube-gradle-plugin/2.0.1/sonarqube-gradle-plugin-2.0.1.pom'.   All tests are passing locally.

**Comment by falkorichter** [comment]
@skraynick code looks fine, I restartet the travis build, it seems to be temp glitch when trying to download that plugin file, I would assume it should work when we try it again.

**Pull request merged**
